app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController

users:
    type:       rest
    resource:   AppBundle\Controller\UserController