app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

tests:
    type:       rest
    resource:   AppBundle\Controller\TestController

json_resource:
    type:       rest
    resource:   AppBundle\Controller\JsonResourceController
